config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
  resources :movies, only: %w[index show] do
    resources :bookmarks, only: %w[new create]
  end
  resources :bookmarks, only: %w[destroy]
  resources :lists, only: %w[index show create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
  validates :list_id, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_movie, only: %w[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie

    if @bookmark.save
      # redirect_to list_path(@bookmark.list)
    else
      # render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list

    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:list_id)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, except: %w[index new create]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy

    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params['movie']
      @movies = Movie.where('title iLIKE ?', "%#{params[:movie]}%")
    else
      @movies = Movie.all
    end

  end

  def show
    @movie = Movie.find(params[:id])
    @lists = List.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @movie, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.submit "Add movie to list", class: "btn btn-dark" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light bg-light w-100 position-fixed my-navbar p-0">
      <div class="d-flex align-items-center w-100 me-5">
        <a class="navbar-brand flex-grow-1 p-0" href="/">
          <%= image_tag "logo/logo.png", alt: "Movee Logo", class: "ms-3", width: 90, height: 90%>
          <%= image_tag "logo/brand.png", alt: "Movee Logo", width: 160, height: 70%>
        </a>
        <%= link_to "My lists", lists_path, class: "btn btn-outline-dark mx-4"%>
        <form class="d-flex" action="/">
          <input class="form-control me-2" name="movie" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container nav-space min-vh-100">
      <%= yield %>
    </div>

    <footer class="footer">
      <p>Made with 🖤 by Paul.</p>
      <div class="socials">
        <a href="#"><%= icon('fa-brands', 'instagram') %></a>
        <a href="#"><%= icon('fa-brands', 'github') %></a>
        <a href="#"><%= icon('fa-brands', 'linkedin') %></a>
      </div>
    </footer>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name, label: 'List name:' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create a new list", class: "btn btn-outline-light" %>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<hr>

<div class="all-my-lists my-5">
  <% if @lists.empty?%>
    <h3>No lists yet...</h3>
  <% else %>
    <% @lists.each do |list| %>
      <div class='list-card'>
        <%= link_to list_path(list) do %>
          <% if list.photo.key %>
            <%= cl_image_tag list.photo.key, class: "list-card-img" %>
          <% else %>
            <img src="https://static.turbosquid.com/Preview/2014/05/22__12_57_23/CAM_01.png970b3cc7-1c24-4379-9d1d-10f0e2fa495dLarge.jpg" alt="" class="list-card-img">
          <% end %>
        <% end %>
        <div class="list-card-body">
          <h4><%= list.name %></h4>
          <p><em>Includes: <%= list.movies[0]&.title %>
          <% list.movies[1..5]&.each do |movie| %>
            <%= ", " if movie %><%= movie&.title %>
          <% end %>
          </em></p>
          <%= link_to "Access list", list_path(list), class: "btn btn-outline-dark" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<hr>

<div id="new-list" class="create-list p-4">
  <h3>Add a list:</h3>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<h1 class="list-title"><%= @list.name %><%= " (#{@list.movies.count})" %></h1>
<hr>

<% if @bookmarks.empty? %>

  <a href="/" class="text-decoration-none">
    <div class="add-movie-btn">
        <p> + Add your first movie<p>
    </div>
  </a>

<% else %>

  <div class="movies-grid my-5">
  <% @bookmarks.each do |bookmark| %>
  <div class="card movie-card grid-item">
      <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %>">
      <div class="card-body d-flex flex-column">
        <h4><%= bookmark.movie.title %></h4>
        <p><em><%= bookmark&.comment %></em></p>
        <p><%= link_to "Delete from #{@list.name}", bookmark_path(bookmark), method: :delete, class: "btn btn-sm btn-dark"%></p>
      </div>
    </div>
  <% end %>
  </div>

<% end %>


<hr>

<%= link_to "Delete List", list_path(@list), method: :delete, data: { confirm: "Are you sure?" }, class: "btn text-white btn-danger mt-3" %>

app/views/movies/index.html.erb
<div class="movies-grid">
  <% @movies.each do |movie| %>
  <div class="card movie-card grid-item">
    <img src="<%= movie.poster_url %>" class="card-img-top" alt="<%= movie.title %>">
    <div class="card-body d-flex flex-column">
      <div class="">
        <h4 class="card-title"><%= movie.title %></h4>
        <p><%= movie.overview.first(40) + "..." %></p>
      </div>
      <%= link_to "More info", movie_path(movie), class: "btn btn-dark mt-auto" %>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="movie-page-card">
  <img src='<%= @movie.poster_url %>' alt="<%= @movie.title %> poster" class="movie-poster">
  <div class="movie-elements">
    <h2><%= @movie.title %></h2>
    <hr>
    <p><%= @movie.overview %></p>
    <h4><strong>⭐ <%= @movie.rating %></strong></h4>
    <div class="dropdown movieBtn">
      <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Add to a list
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% @lists&.each do |list| %>
          <%= link_to list.name, movie_bookmarks_path(@movie, bookmark: { list_id: list.id } ), method: :post, class: 'dropdown-item' %>
        <% end %>
        <hr>
        <%= link_to "+ Add new list", "/lists/#new-list", class: "dd-new-list-btn"%>
      </ul>
    </div>
  </div>
</div>